version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fakenews_network

  detector-ml:
    build:
      context: ./fake-news/detector-ml
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - fakenews_network

  fake-news-ui:
    build:
      context: ./fake-news/fake-news-ui
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "8080:80"
    depends_on:
      - detector-ml
    networks:
      - fakenews_network

networks:
  fakenews_network:
    driver: bridge

volumes:
  mongodb_data:
